application: retail-dataflow-demo
version: 1
runtime: go
api_version: go1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
- url: /swagger
  static_dir: swagger
  secure: always
  login: admin
- url: /.*
  script: _go_app
